/* eslint-disable @next/next/no-img-element -- Local optimized raster shared by Vinext and standalone Vite. */
'use client';
/* Native links support both Vinext and the standalone Vite build. */
/* eslint-disable @next/next/no-html-link-for-pages */
import { ArrowDown, ArrowUpRight, BookOpen, MapPin } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';

import BridgeExplorer from './BridgeExplorer';

import LongThanhExhibition from './LongThanhExhibition';
import SiteShell from './SiteShell';
import './about.css';

const vnexpress = 'https://vnexpress.net/dien-mao-san-bay-long-thanh-trong-tuong-lai-4607669.html';
const vtv = 'https://vtv.vn/san-bay-long-thanh-hang-nghin-nguoi-chay-dua-truoc-gio-g-100251202150621774.htm';
const manufacturer = 'https://www.shinmaywa.co.jp/english/products/paxway/introduction.html';
const panorama = 'https://i1-vnexpress.vnecdn.net/2023/05/21/Anh-1-1684637666.jpg?w=1200&h=0&q=100&dpr=1&fit=crop&s=YjeuYOQri7XHLzMMsNCjdg';

export default function About() {
  const pageRef = useRef<HTMLDivElement>(null);
  const [sourcesOpen, setSourcesOpen] = useState(false);
  useEffect(() => {
    const page = pageRef.current;
    if (!page || !('IntersectionObserver' in window) || window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
    const observer = new IntersectionObserver(entries => entries.forEach(entry => {
      if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); }
    }), { threshold: .08 });
    page.querySelectorAll('[data-reveal]').forEach(section => observer.observe(section));
    return () => observer.disconnect();
  }, []);
  const openSources = () => setSourcesOpen(true);
  return <div className="about-page" ref={pageRef}>
    <SiteShell page="about">
    <main id="about-content" tabIndex={-1} className="about-main">
      <section className="about-hero" aria-labelledby="about-title">
        <div className="about-hero-art"><img className="airport-concept-image" src="/images/airport-concept-ai.webp" alt="Phối cảnh AI nhà ga mái cong, tàu bay và cầu ống dẫn khách trong ánh sáng chiều" width={1672} height={941} fetchPriority="high"/></div>
        <div className="about-shell hero-shell"><div className="about-hero-copy"><span className="about-kicker">PBB LAB / ABOUT</span><h1 id="about-title">Nơi công nghệ<br/>kết nối những<br/><em>hành trình.</em></h1><p>Không gian khám phá, học tập và mô phỏng cầu hành khách trong bối cảnh Cảng hàng không quốc tế Long Thành.</p><div className="about-actions"><a className="about-button" href="/">Khám phá mô phỏng <ArrowUpRight size={19}/></a><a className="about-button secondary" href="#shinmaywa">Tìm hiểu công nghệ <ArrowDown size={17}/></a></div></div><div className="hero-caption"><span><MapPin size={14}/> LONG THÀNH · ĐỒNG NAI</span><span>MINH HỌA AI · KHÔNG PHẢI ẢNH LONG THÀNH THỰC TẾ</span></div></div>
      </section>
      <nav className="about-chapters about-shell" aria-label="Các phần của trang About"><a href="#long-thanh"><span>01</span> Sân bay</a><a href="#shinmaywa"><span>02</span> Công nghệ</a><a href="#experience"><span>03</span> Trải nghiệm</a><a href="#philosophy"><span>04</span> Triết lý</a><a href="#exhibition"><span>05</span> Triển lãm</a><a href="#sources" onClick={openSources}><BookOpen size={14}/> Nguồn công khai</a></nav>
      <section id="long-thanh" className="about-shell about-section" data-reveal aria-labelledby="airport-title">
        <div className="editorial-heading"><span className="about-kicker">01 / BỐI CẢNH CỦA NHỮNG KẾT NỐI</span><h2 id="airport-title">Một sân bay lớn.<br/>Từng điểm kết nối.</h2></div>
        <div className="about-editorial"><p className="about-lead">Ở Long Thành, hành trình hàng không bắt đầu từ sự phối hợp giữa kiến trúc, hạ tầng và con người.</p><div><p>Cảng hàng không quốc tế Long Thành tại Đồng Nai được định hướng phát triển thành cửa ngõ hàng không quy mô lớn. Kiến trúc nhà ga lấy cảm hứng từ hoa sen, còn mạng lưới sân đỗ và các công trình phục vụ tạo nên nền tảng cho hoạt động khai thác.</p><p>Từ nhà ga, hành khách đi qua cầu cố định, qua cầu hành khách rồi tới cửa tàu bay. Ở phía dưới, sân đỗ là nơi các thiết bị và nhân viên mặt đất phối hợp phục vụ chuyến bay. PBB nằm ngay tại điểm giao nhau của hai dòng hoạt động ấy.</p></div></div>
        <div className="about-stats" aria-label="Số liệu quy mô và công suất thiết kế"><div><span className="stat-scope">TOÀN DỰ ÁN / QUY HOẠCH</span><strong>5.000 <small>ha</small></strong><p>Diện tích dự án Long Thành</p><a href="#sources" onClick={openSources}>Nguồn: VTV · 02/12/2025 ↗</a></div><div><span className="stat-scope">GIAI ĐOẠN 1 / THIẾT KẾ</span><strong>25 <small>triệu</small></strong><p>Hành khách mỗi năm</p><a href="#sources" onClick={openSources}>Nguồn: VTV · 02/12/2025 ↗</a></div><div><span className="stat-scope">GIAI ĐOẠN 1 / THIẾT KẾ</span><strong>1,2 <small>triệu tấn</small></strong><p>Hàng hóa mỗi năm</p><a href="#sources" onClick={openSources}>Nguồn: VTV · 02/12/2025 ↗</a></div></div>
        <p className="about-note">Các số liệu mô tả phạm vi quy hoạch và công suất thiết kế, không phải sản lượng khai thác thực tế hay xác nhận tình trạng vận hành hiện tại.</p>
      </section>
      <section className="about-visual-story" aria-labelledby="architecture-title" data-reveal><figure className="original-airport-figure"><img className="airport-concept-image" src={panorama} alt="Phối cảnh tổng thể Cảng hàng không quốc tế Long Thành, ảnh ACV đăng trên VnExpress" loading="lazy" referrerPolicy="no-referrer"/><figcaption>PHỐI CẢNH LONG THÀNH · ẢNH: ACV / <a href={vnexpress} target="_blank" rel="noopener noreferrer">VNEXPRESS · 21/05/2023 ↗</a></figcaption></figure><div><span className="about-kicker">TỪ KIẾN TRÚC ĐẾN SÂN ĐỖ</span><h2 id="architecture-title">Nhà ga mở ra.<br/>Cầu nối tiếp hành trình.</h2><p>Vẻ rộng lớn của sân bay trở nên gần gũi ở từng vị trí đỗ. Tại đây, một cơ cấu có thể xoay, nâng và thay đổi tầm với đưa lối đi từ nhà ga đến sát cửa tàu bay.</p><blockquote className="press-excerpt"><p>“lấy hình ảnh hoa sen làm ý tưởng chính”</p><cite>Phước Tuấn · VnExpress · 21/05/2023</cite></blockquote><a className="about-text-link" href={vnexpress} target="_blank" rel="noopener noreferrer">Xem bài và ảnh gốc trên VnExpress <ArrowUpRight size={17}/></a></div></section>
      <section id="shinmaywa" className="about-shell about-section technology-section" data-reveal aria-labelledby="technology-title"><div className="editorial-heading"><span className="about-kicker">02 / CÔNG NGHỆ TẠI ĐIỂM KẾT NỐI</span><h2 id="technology-title">ShinMaywa<br/><span>Passenger Boarding Bridge.</span></h2></div><div className="about-editorial"><p className="about-lead">Một lối đi liên tục.<br/>Nhiều cơ cấu phối hợp.</p><div><p>PAXWAY là dòng cầu hành khách của ShinMaywa. Cầu kết nối nhà ga với cửa tàu bay, cho phép điều chỉnh hướng tiếp cận, tầm với và cao độ để tạo lối lên xuống cho hành khách.</p><p>Sơ đồ dưới đây giới thiệu các bộ phận trong mô hình PBB Lab. Đây là hình minh họa phục vụ học tập, không xác nhận model, kích thước hoặc cấu hình lắp đặt cụ thể tại Long Thành.</p><a className="about-text-link" href={manufacturer} target="_blank" rel="noopener noreferrer">Thông tin sản phẩm từ ShinMaywa <ArrowUpRight size={16}/></a></div></div><BridgeExplorer/>
        <div className="motion-story"><div><span className="about-kicker amber">CHUYỂN ĐỘNG CÓ MỤC ĐÍCH</span><h3>Tới đúng vị trí.<br/>Ở đúng cao độ.</h3></div><ol><li><span>01</span><div><h4>Tiếp cận & thu–duỗi</h4><p>Cụm di chuyển phối hợp với các đoạn ống lồng để đưa cabin tới vùng cửa tàu bay.</p></div></li><li><span>02</span><div><h4>Nâng–hạ & quay cabin</h4><p>Cơ cấu nâng điều chỉnh cao độ; cabin quay để căn hướng đầu cầu với cửa.</p></div></li><li><span>03</span><div><h4>Điều chỉnh góc sàn cabin</h4><p>Trang sản phẩm công khai của ShinMaywa giới thiệu khả năng điều chỉnh góc sàn cabin để thích ứng với độ nghiêng giữa sàn ống lồng và sàn tàu bay.</p><small>Thông tin chung của dòng sản phẩm; không xác nhận cấu hình tại Long Thành.</small></div></li></ol></div>
      </section>
      <section className="connection-study about-shell" aria-labelledby="connection-title"><div><span className="about-kicker">TỪ NHÀ GA ĐẾN TÀU BAY</span><h2 id="connection-title">Một kết nối.<br/>Cả một hành trình.</h2><p>Cầu hành khách tạo nên lối đi liên tục giữa nhà ga và tàu bay, nối ba không gian trong cùng một hành trình.</p><ol><li><span>01</span><div><h3>Nhà ga</h3><p>Nơi hành khách chuẩn bị bước vào hành trình bay.</p></div></li><li><span>02</span><div><h3>Cầu hành khách</h3><p>Kết nối lối ra cửa khởi hành với cửa tàu bay.</p></div></li><li><span>03</span><div><h3>Tàu bay</h3><p>Điểm tiếp nối từ không gian mặt đất đến chuyến bay.</p></div></li></ol></div></section>
      <section id="experience" className="experience-band" data-reveal aria-labelledby="experience-title"><div className="about-shell"><div className="editorial-heading"><span className="about-kicker">03 / PBB LAB</span><h2 id="experience-title">Biến kiến thức<br/>thành trải nghiệm.</h2></div><div className="experience-intro"><p>Đọc tên một bộ phận là bước đầu.<br/>Quan sát nó chuyển động giúp hiểu điều gì đang diễn ra.</p><a className="about-button" href="/">Vào không gian 3D <ArrowUpRight size={19}/></a></div><div className="experience-list"><article><span>01 / KHÔNG GIAN</span><h3>Khám phá trong 3D</h3><p>Xoay và thu phóng góc nhìn, chuyển tới cabin hoặc nhìn từ trên cao; bật nhãn để nhận diện bộ phận.</p></article><article><span>02 / CƠ CẤU</span><h3>Hiểu qua chuyển động</h3><p>Điều chỉnh hướng xoay, chiều dài, cao độ và góc cabin. Quan sát kết quả ngay trên mô hình.</p></article><article><span>03 / TRẠNG THÁI</span><h3>Quan sát thiết bị</h3><p>Theo dõi thông số, trạng thái nguồn và canopy; xem góc CCTV mô phỏng từ cabin cùng phản hồi của đèn, quạt và điều hòa.</p></article><article><span>04 / TÌNH HUỐNG</span><h3>Học cả một chu trình</h3><p>Chọn thủ công hoặc hướng dẫn để khám phá tiếp cận, phục vụ và tách cầu; thử tạm dừng, dừng khẩn cấp và các điều kiện chặn chuyển động.</p></article></div><p className="experience-limit">Phạm vi hiện có: mô hình minh họa và liên động học tập. Chưa mô phỏng tải trọng, thủy lực, cảm biến thật, Autoleveler hoặc thao tác cấp điện, khí và nước cho tàu bay. Chế độ hướng dẫn không đồng nghĩa với tự động vận hành thiết bị thật.</p></div></section>
      <section id="philosophy" className="about-shell about-section philosophy-section" data-reveal aria-labelledby="philosophy-title"><span className="about-kicker">04 / TRIẾT LÝ XÂY DỰNG</span><h2 id="philosophy-title">Dễ hiểu hơn.<br/>Có căn cứ hơn.</h2><div className="philosophy-list"><article><span>01</span><div><h3>Trực quan để dễ hiểu.</h3><p>Đặt cấu tạo và chuyển động trong cùng một không gian, giúp người học liên hệ tên gọi với chức năng.</p></div></article><article><span>02</span><div><h3>Có căn cứ kỹ thuật để tăng độ sát thực tế.</h3><p>Diễn giải kiến thức phổ thông từ thông tin sản phẩm công khai; phân biệt công nghệ thực tế với những giản lược của mô phỏng.</p></div></article><article><span>03</span><div><h3>Chú trọng điều kiện vận hành và an toàn.</h3><p>Đưa xác nhận khu vực, quyền tiếp cận, canopy và dừng khẩn cấp vào trải nghiệm để người học thấy mối quan hệ giữa điều kiện và chuyển động.</p></div></article></div></section>
      <section className="about-shell press-section" aria-labelledby="press-title" data-reveal><div className="press-heading"><span className="about-kicker">TƯ LIỆU BÁO CHÍ</span><h2 id="press-title">Nhìn lại một thời điểm.</h2><p>Các liên kết dưới đây dẫn đến ảnh phối cảnh và ảnh công trường tại website báo. Mỗi tư liệu có ngày xuất bản, không đại diện cho hiện trạng hôm nay.</p></div><article className="press-feature"><figure className="press-reference"><span className="about-kicker">VTV / TƯ LIỆU BÁO CHÍ</span><h3>Sân bay Long Thành: Hàng nghìn người &apos;chạy đua&apos; trước giờ G</h3><p>P.V · 02/12/2025 · 20:34 GMT+7</p><a className="about-button secondary" href={vtv} target="_blank" rel="noopener noreferrer">Xem phóng sự ảnh tại nguồn <ArrowUpRight size={17}/></a></figure><div><span className="about-kicker">VTV / PHÓNG SỰ ẢNH</span><h3>Long Thành qua những khung hình công trường</h3><p>Tóm tắt: bài VTV ghi lại công trường nhà ga cùng các hạng mục kết nối tại thời điểm xuất bản.</p><blockquote className="press-excerpt"><p>“công suất 25 triệu hành khách/năm”</p><cite>P.V · VTV · 02/12/2025 · Trích đoạn về thiết kế giai đoạn 1</cite></blockquote><a className="about-text-link" href={vtv} target="_blank" rel="noopener noreferrer">Đọc bài gốc trên VTV <ArrowUpRight size={17}/></a></div></article><p className="about-note">Các đoạn trích được giới hạn ngắn, kèm nguồn và liên kết bài gốc. Ảnh phối cảnh được dẫn từ VnExpress, ghi nguồn ACV; ảnh AI ở đầu trang có chú thích riêng.</p></section>
      <LongThanhExhibition/>
      <section id="sources" className="about-shell about-sources" aria-labelledby="sources-title"><details open={sourcesOpen} onToggle={event => setSourcesOpen(event.currentTarget.open)}><summary><span><BookOpen size={19}/> <span id="sources-title">Nguồn thông tin công khai</span></span><span>{sourcesOpen ? 'Thu gọn −' : 'Mở danh mục +'}</span></summary><div className="source-list"><article><h3>ShinMaywa · PAXWAY</h3><p>Giới thiệu công khai về dòng cầu hành khách và công nghệ điều chỉnh sàn cabin. Thông tin sản phẩm chung không xác nhận cấu hình lắp đặt tại Long Thành.</p><a className="about-text-link" href={manufacturer} target="_blank" rel="noopener noreferrer">Trang sản phẩm của nhà sản xuất <ArrowUpRight size={15}/></a></article><article><h3>VnExpress · 21/05/2023</h3><p>Bài: Diện mạo sân bay Long Thành trong tương lai. Tác giả: Phước Tuấn; đăng lúc 10:55 ngày 21/05/2023. Ảnh phối cảnh trong phần kiến trúc được dẫn trực tiếp từ bài báo, ghi nguồn ACV.</p><a className="about-text-link" href={vnexpress} target="_blank" rel="noopener noreferrer">Đọc bài gốc <ArrowUpRight size={15}/></a></article><article><h3>VTV · 02/12/2025</h3><p>Tác giả: P.V; đăng lúc 20:34 ngày 02/12/2025. Nguồn công khai cho số liệu quy hoạch, công suất thiết kế giai đoạn 1 và tư liệu công trường.</p><a className="about-text-link" href={vtv} target="_blank" rel="noopener noreferrer">Đọc bài gốc <ArrowUpRight size={15}/></a></article></div></details></section>
      <section className="about-closing" data-reveal aria-labelledby="closing-title"><div className="about-shell"><span className="about-kicker">TỪ TÌM HIỂU ĐẾN TỰ KHÁM PHÁ</span><h2 id="closing-title">Bước vào<br/><em>không gian vận hành.</em></h2><p>Chọn một góc nhìn. Thử một chuyển động.<br/>Quan sát cách từng bộ phận cùng tạo nên sự kết nối.</p><div className="about-actions"><a className="about-button" href="/">Khám phá mô phỏng <ArrowUpRight size={19}/></a><a className="about-button secondary" href="#sources" onClick={openSources}>Xem nguồn công khai <BookOpen size={17}/></a></div></div></section>
    </main>
    </SiteShell>
  </div>;
}
