import { useEffect,useRef,useState,Component,type ReactNode } from 'react';
import { Plane,RotateCcw,Maximize,Focus,Layers,Play,Pause,ArrowRight,Info,MousePointer2 } from 'lucide-react';
import { Tabs,TabsList,TabsTrigger } from '@/components/ui/tabs';
import { Switch } from '@/components/ui/switch';
import { command,initial,tick,metrics,status,type Command,type State } from '@/lib/simulation';
import Scene from './Scene';import Controls from './Controls';import Guide from './Guide';
class SceneBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true};}render(){return this.state.failed?<div className="webgl-error">Không thể khởi tạo WebGL. Hãy bật tăng tốc đồ họa trong trình duyệt rồi tải lại trang.</div>:this.props.children;}}
export default function Lab(){
 const [s,setS]=useState(initial);const live=useRef(s);const [labels,setLabels]=useState(true);const [view,setView]=useState('overview');const [cameraReset,setCameraReset]=useState(0);
 const send=(c:Command)=>{live.current=command(live.current,c);setS(live.current);return live.current;};
 useEffect(()=>{let id=0,last=performance.now();const frame=(now:number)=>{const next=tick(live.current,(now-last)/1000);last=now;if(next!==live.current){live.current=next;setS(next);}id=requestAnimationFrame(frame);};id=requestAnimationFrame(frame);return ()=>cancelAnimationFrame(id);},[]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{void Promise.resolve(context.registerTool({name:'pbb_status',description:'Read educational PBB simulation state and safety interlocks.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object.');return {state:status(live.current),pose:live.current.pose,clearance:live.current.authorized,emergency:live.current.emergency};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return ()=>lifecycle.abort();},[]);
 const m=metrics(s.pose);const reset=()=>{send({type:'reset'});setLabels(true);setView('overview');setCameraReset(v=>v+1);};
 return <main>
  <header className="topbar"><a className="brand" href="#"><span className="brand-icon"><Plane size={24}/></span><b>PBB<span>LAB</span></b><span className="brand-divider"/><span className="brand-caption">KHÔNG GIAN HỌC TẬP TƯƠNG TÁC</span></a><span className="training-badge">MÔ PHỎNG ĐÀO TẠO</span></header>
  <div className="page-title"><div><div className="eyebrow">KỸ THUẬT MẶT ĐẤT / CẦU HÀNH KHÁCH</div><h1>Từ nhà ga đến cửa tàu bay<span>.</span></h1><p>Khám phá cấu tạo và vận hành cầu ống lồng trong không gian 3D.</p></div><button className="reset-all" onClick={reset}><RotateCcw size={16}/>Đặt lại bài học</button></div>
  <div className="workspace"><section className="simulation-panel"><div className="simulation-toolbar"><Tabs value={s.mode} onValueChange={mode=>send({type:'mode',mode:mode as State['mode']})}><TabsList><TabsTrigger value="manual">Điều khiển thủ công</TabsTrigger><TabsTrigger value="guide">Chế độ hướng dẫn</TabsTrigger></TabsList></Tabs><label className="label-toggle"><Switch checked={labels} onCheckedChange={setLabels} aria-label="Nhãn bộ phận"/>Nhãn bộ phận</label></div>
   <div className="viewport"><SceneBoundary><Scene s={s} labels={labels} view={view} reset={cameraReset}/></SceneBoundary><div className="scene-badge"><span className="live-dot"/>VỊ TRÍ ĐỖ A04<small>GÓC NHÌN 3D • THỜI GIAN THỰC</small></div><div className="camera-controls"><button className={view==='overview'?'selected':''} onClick={()=>setView('overview')} title="Góc nhìn tổng thể" aria-label="Góc nhìn tổng thể"><Maximize size={19}/></button><button className={view==='cabin'?'selected':''} onClick={()=>setView('cabin')} title="Góc nhìn gần cabin" aria-label="Góc nhìn gần cabin"><Focus size={19}/></button><button className={view==='top'?'selected':''} onClick={()=>setView('top')} title="Nhìn từ trên" aria-label="Nhìn từ trên"><Layers size={19}/></button><button onClick={()=>setCameraReset(v=>v+1)} title="Đặt lại camera" aria-label="Đặt lại camera"><RotateCcw size={18}/></button></div><div className="scene-help"><MousePointer2 size={14}/> Kéo để xoay · Cuộn để thu phóng</div><div className={'state-pill '+(s.emergency?'danger':'')}>{status(s)}</div></div>
   <div className="telemetry"><div><span>GÓC XOAY</span><strong>{s.pose.angle.toFixed(1)}<small>°</small></strong></div><div><span>CAO ĐỘ SÀN</span><strong>{s.pose.height.toFixed(2)}<small>m</small></strong></div><div><span>KHOẢNG HỞ THÂN</span><strong className={m.gap<.65?'warning':''}>{m.gap.toFixed(2)}<small>m</small></strong></div><div><span>LỆCH NGANG CỬA</span><strong>{Math.abs(m.offset).toFixed(2)}<small>m</small></strong></div></div>
   <div className="playback"><div className="playback-actions">{s.mode==='guide'?<><button className="primary" onClick={()=>send({type:'guide'})}><Play size={16}/>Tiếp cận</button><button onClick={()=>send({type:'guide',departure:true})}>Tách cầu<ArrowRight size={16}/></button></>:<span className="action-label">{s.action}</span>}<button aria-label={s.paused?'Tiếp tục':'Tạm dừng'} onClick={()=>send({type:'pause'})}>{s.paused?<Play size={16}/>:<Pause size={16}/>}<span>{s.paused?'Tiếp tục':'Tạm dừng'}</span></button></div><div className="speed"><span>Tốc độ</span>{[.5,1,2].map(v=><button key={v} className={s.speed===v?'active':''} onClick={()=>send({type:'speed',value:v})}>{v}×</button>)}</div></div>
   <div className={'feedback '+(s.message.includes('chặn')?'blocked':'')} role="status" aria-live="polite"><Info size={17}/><span>{s.message}</span></div>
  </section><Controls s={s} send={send}/></div>
  <Guide s={s}/><footer><Info size={15}/><span>Chỉ dùng để học tập và thuyết trình. Không phải phần mềm điều khiển thiết bị thật hay quy trình vận hành chính thức của sân bay.</span><b>PBB LAB / 01</b></footer>
 </main>;
}


